# Fly.io configuration file (optional - only if using Fly.io)

app = "pixel-chat"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"

[processes]
  app = "streamlit run app.py --server.port=8080 --server.address=0.0.0.0 --server.headless=true"

